/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VendaDeAlimentos;

/**
 *
 * @author geral
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTGenrenciAlimentos = new javax.swing.JLabel();
        TXTAlimentosNome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlanilhaAlimentos = new javax.swing.JTable();
        BotãoNovoAlimento = new javax.swing.JButton();
        BotãoEditarAlimento = new javax.swing.JButton();
        BotãoRemoverAlimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda De Alimentos");

        TXTGenrenciAlimentos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TXTGenrenciAlimentos.setText("Gerência de Alimentos");

        TXTAlimentosNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTAlimentosNome.setText("Lista de Alimentos:");

        PlanilhaAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Codigo"
            }
        ));
        jScrollPane1.setViewportView(PlanilhaAlimentos);

        BotãoNovoAlimento.setText("Novo");
        BotãoNovoAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoNovoAlimentoActionPerformed(evt);
            }
        });

        BotãoEditarAlimento.setText("Editar");
        BotãoEditarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoEditarAlimentoActionPerformed(evt);
            }
        });

        BotãoRemoverAlimento.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(BotãoNovoAlimento)
                        .addGap(135, 135, 135)
                        .addComponent(BotãoEditarAlimento)
                        .addGap(77, 77, 77)
                        .addComponent(BotãoRemoverAlimento))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(TXTGenrenciAlimentos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTAlimentosNome)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(TXTGenrenciAlimentos)
                .addGap(60, 60, 60)
                .addComponent(TXTAlimentosNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotãoNovoAlimento)
                    .addComponent(BotãoEditarAlimento)
                    .addComponent(BotãoRemoverAlimento))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotãoNovoAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoNovoAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotãoNovoAlimentoActionPerformed

    private void BotãoEditarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoEditarAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotãoEditarAlimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoEditarAlimento;
    private javax.swing.JButton BotãoNovoAlimento;
    private javax.swing.JButton BotãoRemoverAlimento;
    private javax.swing.JTable PlanilhaAlimentos;
    private javax.swing.JLabel TXTAlimentosNome;
    private javax.swing.JLabel TXTGenrenciAlimentos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
