/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemax.frontend.login;
import cinemax.backend.funcionarios.CargoFuncionario;
import cinemax.backend.funcionarios.Funcionario;
import cinemax.backend.funcionarios.IBancoDeDadosFuncionario;
import cinemax.frontend.PaginasGeranteeFuncionario.Funcionarios;
import cinemax.frontend.PaginasGeranteeFuncionario.Gerente;
import cinemax.frontend.controller.ControladorDeApp;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author geral
 */
public class LoginDeAcesso extends javax.swing.JFrame {
	private IBancoDeDadosFuncionario bancoFuncionarios = ControladorDeApp.getInstancia()
			.getBackend().getBancoFuncionarios();
  
    public LoginDeAcesso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TXTLoginAcessso = new javax.swing.JLabel();
        TXTUsuarioLogin = new javax.swing.JLabel();
        TXTSenhaLogin = new javax.swing.JLabel();
        CapturaDeTXTUsuarioLogin = new javax.swing.JTextField();
        BotaoLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CapturaDeTXTSenhaLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login de Acesso");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 32, 64));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TXTLoginAcessso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TXTLoginAcessso.setText("Login");

        TXTUsuarioLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTUsuarioLogin.setText("Usuario");

        TXTSenhaLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTSenhaLogin.setText("Senha");

        CapturaDeTXTUsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturaDeTXTUsuarioLoginActionPerformed(evt);
            }
        });

        BotaoLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotaoLogin.setText("Entar");
        BotaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(9)
        					.addComponent(jLabel3)
        					.addGap(18)
        					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(TXTUsuarioLogin)
        						.addComponent(TXTSenhaLogin)
        						.addComponent(CapturaDeTXTUsuarioLogin, GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        						.addComponent(CapturaDeTXTSenhaLogin))
        					.addGap(113))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(TXTLoginAcessso)
        							.addGap(227))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(BotaoLogin, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        							.addGap(204))))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(92)
        			.addComponent(TXTLoginAcessso)
        			.addGap(94)
        			.addComponent(TXTUsuarioLogin)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(CapturaDeTXTUsuarioLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel3))
        				.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(21)
        			.addComponent(TXTSenhaLogin)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(CapturaDeTXTSenhaLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(40)
        			.addComponent(BotaoLogin, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(212, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CapturaDeTXTUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturaDeTXTUsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapturaDeTXTUsuarioLoginActionPerformed

    private void BotaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLoginActionPerformed
    	String cpf = CapturaDeTXTUsuarioLogin.getText();
	    String senha = new String(CapturaDeTXTSenhaLogin.getPassword());
	    
	    CargoFuncionario cargo = bancoFuncionarios.login(cpf, senha);
	    
	    if(cargo == null) {
	    	javax.swing.JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos!");
	    	return;
	    }

	    ControladorDeApp.getInstancia().onLogin(cargo);
	    if (cargo == CargoFuncionario.Atendente) {
	        // Abre a tela dos funcionários
	        Funcionarios telaFuncionario = new Funcionarios();
	        telaFuncionario.setVisible(true);
	    } else {
	        // Abre a tela do gerente/admin
	        Gerente telaGerente = new Gerente();
	        telaGerente.setVisible(true);
	    }
        this.dispose();
    }//GEN-LAST:event_BotaoLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDeAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDeAcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoLogin;
    private javax.swing.JPasswordField CapturaDeTXTSenhaLogin;
    private javax.swing.JTextField CapturaDeTXTUsuarioLogin;
    private javax.swing.JLabel TXTLoginAcessso;
    private javax.swing.JLabel TXTSenhaLogin;
    private javax.swing.JLabel TXTUsuarioLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
