
package cinemax.frontend.vendadealimentos;
import cinemax.backend.alimentos.Alimento;
import cinemax.frontend.controller.ControladorDeApp;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Map;
import java.util.HashMap;
 
public class CarrinhoDeComprasAlimentos extends javax.swing.JFrame {
 private DefaultTableModel modeloTabela;
    private ControladorDeApp app = ControladorDeApp.getInstancia();
    
    
    /**
     * Creates new form CarrinhoDeComprasAlimentos
     */
    public CarrinhoDeComprasAlimentos() {
        initComponents();
         configurarTabela();
        configurarEstilos();
       
    }
 
 private void configurarTabela() {
        modeloTabela = (DefaultTableModel) TabelaCarrinho.getModel();
        modeloTabela.setColumnIdentifiers(new String[]{"Item", "Preço Unitário", "Quantidade", "Subtotal"});
    }
 
 
 
 
   private void configurarEstilos() {
        // Configuração de cores e fontes
        getContentPane().setBackground(new Color(2, 32, 64));
        TabelaCarrinho.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        TabelaCarrinho.getTableHeader().setBackground(new Color(2, 32, 64));
        TabelaCarrinho.getTableHeader().setForeground(Color.WHITE);
        TabelaCarrinho.setRowHeight(25);
        
        Comprar.setBackground(new Color(0, 153, 51)); // Verde
        Comprar.setForeground(Color.WHITE);
        Voltar.setBackground(new Color(204, 0, 0)); // Vermelho
        Voltar.setForeground(Color.WHITE);
        
        Total.setFont(new Font("Tahoma", Font.BOLD, 14));
    }

     public void adicionarItens(Map<Alimento, Integer> itens) {
        modeloTabela.setRowCount(0);
        double total = 0;
        
        for (Map.Entry<Alimento, Integer> entry : itens.entrySet()) {
            Alimento alimento = entry.getKey();
            int quantidade = entry.getValue();
            double subtotal = alimento.getPreco() * quantidade;
            total += subtotal;
            
            modeloTabela.addRow(new Object[]{
                alimento.getNome(),
                String.format("R$ %.2f", alimento.getPreco()),
                quantidade,
                String.format("R$ %.2f", subtotal)
            });
        }
        
        // Atualiza o total
        Total.setText(String.format("R$ %.2f", total));
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCarrinho = new javax.swing.JTable();
        Comprar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(2, 32, 64));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new Color(2, 17, 28));

        TabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Preço", "Quantidade", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(TabelaCarrinho);

        Comprar.setText("Comprar");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Total da compra:");

        Total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Total.setText("0");

        jLabel2.setText("R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Total)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Comprar)
                        .addGap(81, 81, 81)
                        .addComponent(Voltar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comprar)
                    .addComponent(Voltar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
         dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
         if (modeloTabela.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, 
            "Não há itens no carrinho!", 
            "Aviso", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    int confirm = JOptionPane.showConfirmDialog(this,
        "Confirmar compra no valor de " + Total.getText() + "?",
        "Confirmação de Compra",
        JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // 1. Registrar a venda (mantém seu código atual)
            Map<Alimento, Integer> itens = new HashMap<>();
            for (int i = 0; i < modeloTabela.getRowCount(); i++) {
                String nome = (String) modeloTabela.getValueAt(i, 0);
                double preco = Double.parseDouble(
                    ((String) modeloTabela.getValueAt(i, 1)).replace("R$ ", ""));
                int quantidade = (Integer) modeloTabela.getValueAt(i, 2);
                
                Alimento alimento = new Alimento(nome, preco, 0);
                itens.put(alimento, quantidade);
            }
            
            app.getBackend().getGerenciadorRelatorios()
               .obterRelatorioDoDia()
               .getRelatorioAlimentos()
               .adicionarVendas(itens);
            
            // 2. Limpar o carrinho atual
            modeloTabela.setRowCount(0);
            Total.setText("0");
            
            // 3. Fechar o carrinho
            this.dispose();
            
            // 4. Limpar a tela de vendas usando reflexão
            for (Window window : Window.getWindows()) {
                if (window instanceof TelaVendaDeAlimento) {
                    TelaVendaDeAlimento telaVenda = (TelaVendaDeAlimento) window;
                    
                    // Limpa os campos usando reflexão
                    try {
                        // Limpa o campo de item selecionado
                        JLabel txtItemSelecionado = (JLabel) telaVenda.getClass()
                            .getDeclaredField("TXTitemSelecionado").get(telaVenda);
                        txtItemSelecionado.setText("");
                        
                        // Limpa os totais
                        JLabel txtQuantidade = (JLabel) telaVenda.getClass()
                            .getDeclaredField("TXTQuantidadeDeitemTotaisSelecionados").get(telaVenda);
                        txtQuantidade.setText("0");
                        
                        JLabel txtPrecoTotal = (JLabel) telaVenda.getClass()
                            .getDeclaredField("TXTPrecoTotalDeTodosOsItems").get(telaVenda);
                        txtPrecoTotal.setText("0");
                        
                        // Limpa o carrinho interno (HashMap)
                        Map<Alimento, Integer> carrinho = (Map<Alimento, Integer>) telaVenda.getClass()
                            .getDeclaredField("carrinho").get(telaVenda);
                        carrinho.clear();
                        
                        // Traz a tela de vendas para frente
                        telaVenda.toFront();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,
                            "Compra registrada, mas não foi possível limpar todos os campos.\n" +
                            "Erro: " + e.getMessage(),
                            "Aviso",
                            JOptionPane.WARNING_MESSAGE);
                    }
                    break;
                }
            }
            
            JOptionPane.showMessageDialog(null,
                "Compra registrada com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erro ao processar compra: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_ComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrinhoDeComprasAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrinhoDeComprasAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrinhoDeComprasAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrinhoDeComprasAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarrinhoDeComprasAlimentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comprar;
    private javax.swing.JTable TabelaCarrinho;
    private javax.swing.JLabel Total;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
