/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemax.frontend.vendadealimentos;

/**
 *
 * @author geral
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TXTGenrenciAlimentos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlanilhaAlimento = new javax.swing.JTable();
        TXTNomeAlimento = new javax.swing.JLabel();
        TXTPrecoAlimento = new javax.swing.JLabel();
        TXTCodigoAlimento = new javax.swing.JLabel();
        CapturaTXTCodigoAlimento = new javax.swing.JTextField();
        CapturaTXTNomeAlimento = new javax.swing.JTextField();
        CapturaTXTPrecoAlimento = new javax.swing.JTextField();
        ButaoCadastrarAlimento = new javax.swing.JButton();
        ButaoEditarAlimento = new javax.swing.JButton();
        ButaoRemoverAlimento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CapturaTXTProcurarNomeAlimento = new javax.swing.JTextField();
        ButaoProcurarAlimentoNome = new javax.swing.JButton();
        TXTProcurarNomeAlimento = new javax.swing.JLabel();
        TXTProcurarCodigoAlimento = new javax.swing.JLabel();
        CapturaTXTProcurarCodigoAlimento = new javax.swing.JTextField();
        ButaoProcurarCodigoAlimento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda De Alimentos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TXTGenrenciAlimentos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TXTGenrenciAlimentos.setForeground(new java.awt.Color(0, 32, 64));
        TXTGenrenciAlimentos.setText("Gerência de Alimentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(TXTGenrenciAlimentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(TXTGenrenciAlimentos)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 32, 64));
        jPanel2.setForeground(new java.awt.Color(0, 32, 64));

        PlanilhaAlimento.setBackground(new java.awt.Color(242, 242, 242));
        PlanilhaAlimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Código"
            }
        ));
        jScrollPane1.setViewportView(PlanilhaAlimento);

        TXTNomeAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTNomeAlimento.setForeground(new java.awt.Color(255, 255, 255));
        TXTNomeAlimento.setText("Nome");

        TXTPrecoAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTPrecoAlimento.setForeground(new java.awt.Color(255, 255, 255));
        TXTPrecoAlimento.setText("Preço");

        TXTCodigoAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTCodigoAlimento.setForeground(new java.awt.Color(255, 255, 255));
        TXTCodigoAlimento.setText("Código");

        CapturaTXTPrecoAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturaTXTPrecoAlimentoActionPerformed(evt);
            }
        });

        ButaoCadastrarAlimento.setText("Novo");

        ButaoEditarAlimento.setText("Editar");

        ButaoRemoverAlimento.setText("Remover");

        ButaoProcurarAlimentoNome.setText("Procurar");

        TXTProcurarNomeAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTProcurarNomeAlimento.setForeground(new java.awt.Color(0, 32, 64));
        TXTProcurarNomeAlimento.setText("Procure Nome");

        TXTProcurarCodigoAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTProcurarCodigoAlimento.setForeground(new java.awt.Color(0, 32, 64));
        TXTProcurarCodigoAlimento.setText("Procurar Código");

        ButaoProcurarCodigoAlimento.setText("Procurar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TXTProcurarNomeAlimento)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TXTProcurarCodigoAlimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CapturaTXTProcurarNomeAlimento)
                    .addComponent(CapturaTXTProcurarCodigoAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButaoProcurarAlimentoNome)
                    .addComponent(ButaoProcurarCodigoAlimento))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapturaTXTProcurarNomeAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTProcurarNomeAlimento)
                    .addComponent(ButaoProcurarAlimentoNome))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTProcurarCodigoAlimento)
                    .addComponent(CapturaTXTProcurarCodigoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButaoProcurarCodigoAlimento))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(TXTCodigoAlimento)
                        .addGap(18, 18, 18)
                        .addComponent(CapturaTXTCodigoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(TXTNomeAlimento)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(TXTPrecoAlimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CapturaTXTNomeAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(CapturaTXTPrecoAlimento))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(ButaoCadastrarAlimento)
                        .addGap(124, 124, 124)
                        .addComponent(ButaoEditarAlimento)
                        .addGap(97, 97, 97)
                        .addComponent(ButaoRemoverAlimento)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapturaTXTNomeAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTNomeAlimento))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapturaTXTPrecoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTPrecoAlimento))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapturaTXTCodigoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCodigoAlimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButaoCadastrarAlimento)
                    .addComponent(ButaoRemoverAlimento)
                    .addComponent(ButaoEditarAlimento))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CapturaTXTPrecoAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturaTXTPrecoAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapturaTXTPrecoAlimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButaoCadastrarAlimento;
    private javax.swing.JButton ButaoEditarAlimento;
    private javax.swing.JButton ButaoProcurarAlimentoNome;
    private javax.swing.JButton ButaoProcurarCodigoAlimento;
    private javax.swing.JButton ButaoRemoverAlimento;
    private javax.swing.JTextField CapturaTXTCodigoAlimento;
    private javax.swing.JTextField CapturaTXTNomeAlimento;
    private javax.swing.JTextField CapturaTXTPrecoAlimento;
    private javax.swing.JTextField CapturaTXTProcurarCodigoAlimento;
    private javax.swing.JTextField CapturaTXTProcurarNomeAlimento;
    private javax.swing.JTable PlanilhaAlimento;
    private javax.swing.JLabel TXTCodigoAlimento;
    private javax.swing.JLabel TXTGenrenciAlimentos;
    private javax.swing.JLabel TXTNomeAlimento;
    private javax.swing.JLabel TXTPrecoAlimento;
    private javax.swing.JLabel TXTProcurarCodigoAlimento;
    private javax.swing.JLabel TXTProcurarNomeAlimento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
