/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemax.frontend.vendadealimentos;

import cinemax.frontend.PaginasGeranteeFuncionario.Gerente;
import cinemax.backend.alimentos.Alimento; 
import cinemax.backend.alimentos.IBancoDeDadosAlimento;
import cinemax.backend.core.Backend;
import cinemax.frontend.controller.ControladorDeApp;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author geral
 */
public class VendaDealimentoss extends javax.swing.JFrame {
private ControladorDeApp app = ControladorDeApp.getInstancia();
private IBancoDeDadosAlimento bancoDados = app.getBackend().getBancoAlimentos();
 private DefaultTableModel modeloTabela;
 private int indiceSelecionado = -1;
 
 
    /**
     * Creates new form VendaDealimentoss
     */
    public VendaDealimentoss() {
        initComponents();
       inicializarTabela();
       configurarListeners();
       
    }

     private void inicializarTabela() {
      modeloTabela = (DefaultTableModel) PlanilhaDeAlimentos.getModel();


        atualizarTabela();
    }
    
    private void atualizarTabela() {
        modeloTabela.setRowCount(0);
        Alimento[] alimentos = bancoDados.obterTodosAlimentos();
        for (Alimento alimento : alimentos) {
            modeloTabela.addRow(new Object[]{
                alimento.getNome(),
                alimento.getPreco(),
                alimento.getCodigo()
            });
        }
    }
    
    private void configurarListeners() {
       PlanilhaDeAlimentos.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {
                 int linhaSelecionada = PlanilhaDeAlimentos.getSelectedRow(); // CORRIGIDO AQUI
                if (linhaSelecionada != -1) {
                     preencherCampos(linhaSelecionada);
                    indiceSelecionado = linhaSelecionada;
                    
                }
            }
        });
    }
     private void limparCampos() {
       CapturaTXTProcurarNomeAlimento.setText("");
        CapturaTXTProcurarCodigoAlimento.setText("");
     }
     
     private void preencherCampos(int linhaSelecionada) {
    Object valor = PlanilhaDeAlimentos.getValueAt(linhaSelecionada, 0);
    String nome = valor != null ? valor.toString() : "Desconhecido";
    TXTitemSelecionado.setText(nome);
}

     
     
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlanilhaDeAlimentos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        TxtnomeDoalimento = new javax.swing.JLabel();
        TXTcodigodoalimento = new javax.swing.JLabel();
        CapturaTXTProcurarNomeAlimento = new javax.swing.JTextField();
        CapturaTXTProcurarCodigoAlimento = new javax.swing.JTextField();
        bntProcurarnomeAliemnto = new javax.swing.JButton();
        bntProvurarcodigo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTitemSelecionado = new javax.swing.JLabel();
        TXTAcrementoDeItem = new javax.swing.JLabel();
        TXTDecrementoDeItem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTQuantidadeDeitemTotaisSelecionados = new javax.swing.JLabel();
        TXTPrecoTotalDeTodosOsItems = new javax.swing.JLabel();
        bntVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 32, 64));

        jPanel1.setBackground(new java.awt.Color(2, 32, 64));

        PlanilhaDeAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Código"
            }
        ));
        PlanilhaDeAlimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlanilhaDeAlimentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PlanilhaDeAlimentos);

        TxtnomeDoalimento.setText("Procurar Nome:");

        TXTcodigodoalimento.setText("Procurar Código:");

        bntProcurarnomeAliemnto.setText("Procurar");
        bntProcurarnomeAliemnto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProcurarnomeAliemntoActionPerformed(evt);
            }
        });

        bntProvurarcodigo.setText("Procurar");
        bntProvurarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProvurarcodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("-----------------------------------------------------------------");

        jLabel4.setText("Item Selecionado:");

        TXTitemSelecionado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        TXTAcrementoDeItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTAcrementoDeItem.setText("+");

        TXTDecrementoDeItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTDecrementoDeItem.setText("-");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("Total de Item selecionados:");

        jLabel9.setText("Total:");

        TXTQuantidadeDeitemTotaisSelecionados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTQuantidadeDeitemTotaisSelecionados.setText("0");

        TXTPrecoTotalDeTodosOsItems.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TXTPrecoTotalDeTodosOsItems.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(TXTQuantidadeDeitemTotaisSelecionados))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTPrecoTotalDeTodosOsItems)))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXTQuantidadeDeitemTotaisSelecionados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(TXTPrecoTotalDeTodosOsItems)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TxtnomeDoalimento)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(TXTcodigodoalimento)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CapturaTXTProcurarNomeAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(CapturaTXTProcurarCodigoAlimento))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntProvurarcodigo)
                            .addComponent(bntProcurarnomeAliemnto)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(82, 82, 82)
                            .addComponent(TXTitemSelecionado)
                            .addGap(64, 64, 64)
                            .addComponent(TXTAcrementoDeItem)
                            .addGap(29, 29, 29)
                            .addComponent(TXTDecrementoDeItem))
                        .addComponent(jLabel3)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtnomeDoalimento)
                    .addComponent(CapturaTXTProcurarNomeAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntProcurarnomeAliemnto))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTcodigodoalimento)
                    .addComponent(CapturaTXTProcurarCodigoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntProvurarcodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTitemSelecionado)
                    .addComponent(TXTAcrementoDeItem)
                    .addComponent(TXTDecrementoDeItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        bntVoltar.setText("Voltar");
        bntVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntVoltar)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntVoltar)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVoltarActionPerformed
         // Chamando a tela Gerente//
             Gerente telaGerente = new Gerente("usuario", "senha");
            telaGerente.setVisible(true);
            dispose(); 
    }//GEN-LAST:event_bntVoltarActionPerformed

    private void PlanilhaDeAlimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlanilhaDeAlimentosMouseClicked
        
    }//GEN-LAST:event_PlanilhaDeAlimentosMouseClicked

    private void bntProcurarnomeAliemntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProcurarnomeAliemntoActionPerformed
     String nomeProcurado = CapturaTXTProcurarNomeAlimento.getText().trim();
        
        if (nomeProcurado.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Digite um nome para procurar!", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        modeloTabela.setRowCount(0);
        Alimento[] resultados = bancoDados.obterAlimentoPorNome(nomeProcurado);
        
        if (resultados.length == 0) {
            JOptionPane.showMessageDialog(this, 
                "Nenhum alimento encontrado com este nome!", 
                "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Alimento alimento : resultados) {
                modeloTabela.addRow(new Object[]{
                    alimento.getNome(),
                    alimento.getPreco(),
                    alimento.getCodigo()
                });
            }
        }
        limparCampos();
    }//GEN-LAST:event_bntProcurarnomeAliemntoActionPerformed

    private void bntProvurarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProvurarcodigoActionPerformed
      String codigoText = CapturaTXTProcurarCodigoAlimento.getText().trim();
        
        if (codigoText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Digite um código para procurar!", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int codigo = Integer.parseInt(codigoText);
            Alimento alimento = bancoDados.obterAlimentoPorCodigo(codigo);
            
            if (alimento == null) {
                JOptionPane.showMessageDialog(this, 
                    "Nenhum alimento encontrado com este código!", 
                    "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                modeloTabela.setRowCount(0);
                modeloTabela.addRow(new Object[]{
                    alimento.getNome(),
                    alimento.getPreco(),
                    alimento.getCodigo()
                });
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "O código deve ser um número válido!", 
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
        limparCampos();
    }//GEN-LAST:event_bntProvurarcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaDealimentoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaDealimentoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaDealimentoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaDealimentoss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaDealimentoss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CapturaTXTProcurarCodigoAlimento;
    private javax.swing.JTextField CapturaTXTProcurarNomeAlimento;
    private javax.swing.JTable PlanilhaDeAlimentos;
    private javax.swing.JLabel TXTAcrementoDeItem;
    private javax.swing.JLabel TXTDecrementoDeItem;
    private javax.swing.JLabel TXTPrecoTotalDeTodosOsItems;
    private javax.swing.JLabel TXTQuantidadeDeitemTotaisSelecionados;
    private javax.swing.JLabel TXTcodigodoalimento;
    private javax.swing.JLabel TXTitemSelecionado;
    private javax.swing.JLabel TxtnomeDoalimento;
    private javax.swing.JButton bntProcurarnomeAliemnto;
    private javax.swing.JButton bntProvurarcodigo;
    private javax.swing.JButton bntVoltar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}
