
package cinemax.frontend.vendadealimentos;
import cinemax.backend.alimentos.Alimento; 
import cinemax.backend.alimentos.IBancoDeDadosAlimento;
import cinemax.backend.core.Backend;
import cinemax.frontend.PaginasGeranteeFuncionario.Gerente;
import cinemax.frontend.controller.ControladorDeApp;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author geral
 */



public class Vendas extends javax.swing.JFrame {

	private ControladorDeApp app = ControladorDeApp.getInstancia();
	private IBancoDeDadosAlimento bancoDados = app.getBackend().getBancoAlimentos();
    private DefaultTableModel modeloTabela;
    private int indiceSelecionado = -1;
    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
        inicializarTabela();
        configurarListeners();
        
        
           bntRecarregarLista.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        bntRecarregarListaActionPerformed(evt);
    }
});
    }

    
     private void inicializarTabela() {
        modeloTabela = (DefaultTableModel) PlanilhaAlimento.getModel();
        atualizarTabela();
    }
    
    private void configurarListeners() {
        PlanilhaAlimento.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int linhaSelecionada = PlanilhaAlimento.getSelectedRow();
                if (linhaSelecionada != -1) {
                    preencherCampos(linhaSelecionada);
                    indiceSelecionado = linhaSelecionada;
                    ButaoCadastrarAlimento.setEnabled(false);
                }
            }
        });
    }
    
    private void preencherCampos(int linha) {
        CapturaTXTNomeAlimento.setText(modeloTabela.getValueAt(linha, 0).toString());
        CapturaTXTPrecoAlimento.setText(modeloTabela.getValueAt(linha, 1).toString());
        CapturaTXTCodigoAlimento.setText(modeloTabela.getValueAt(linha, 2).toString());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TXTGenrenciAlimentos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlanilhaAlimento = new javax.swing.JTable();
        TXTNomeAlimento = new javax.swing.JLabel();
        TXTPrecoAlimento = new javax.swing.JLabel();
        TXTCodigoAlimento = new javax.swing.JLabel();
        CapturaTXTCodigoAlimento = new javax.swing.JTextField();
        CapturaTXTNomeAlimento = new javax.swing.JTextField();
        CapturaTXTPrecoAlimento = new javax.swing.JTextField();
        ButaoCadastrarAlimento = new javax.swing.JButton();
        ButaoEditarAlimento = new javax.swing.JButton();
        ButaoRemoverAlimento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CapturaTXTProcurarNomeAlimento = new javax.swing.JTextField();
        ButaoProcurarAlimentoNome = new javax.swing.JButton();
        TXTProcurarNomeAlimento = new javax.swing.JLabel();
        TXTProcurarCodigoAlimento = new javax.swing.JLabel();
        CapturaTXTProcurarCodigoAlimento = new javax.swing.JTextField();
        ButaoProcurarCodigoAlimento = new javax.swing.JButton();
        bntRecarregarLista = new javax.swing.JButton();
        ButaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda De Alimentos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TXTGenrenciAlimentos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TXTGenrenciAlimentos.setForeground(new java.awt.Color(0, 32, 64));
        TXTGenrenciAlimentos.setText("Gerência de Alimentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(TXTGenrenciAlimentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(TXTGenrenciAlimentos)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 32, 64));
        jPanel2.setForeground(new java.awt.Color(0, 32, 64));

        PlanilhaAlimento.setBackground(new java.awt.Color(242, 242, 242));
        PlanilhaAlimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Preço", "Código"
            }
        ));
        jScrollPane1.setViewportView(PlanilhaAlimento);

        TXTNomeAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTNomeAlimento.setForeground(new java.awt.Color(255, 255, 255));
        TXTNomeAlimento.setText("Nome");

        TXTPrecoAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTPrecoAlimento.setForeground(new java.awt.Color(255, 255, 255));
        TXTPrecoAlimento.setText("Preço");

        TXTCodigoAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTCodigoAlimento.setForeground(new java.awt.Color(255, 255, 255));
        TXTCodigoAlimento.setText("Código");

        CapturaTXTPrecoAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturaTXTPrecoAlimentoActionPerformed(evt);
            }
        });

        ButaoCadastrarAlimento.setText("Novo");
        ButaoCadastrarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoCadastrarAlimentoActionPerformed(evt);
            }
        });

        ButaoEditarAlimento.setText("Editar");
        ButaoEditarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoEditarAlimentoActionPerformed(evt);
            }
        });

        ButaoRemoverAlimento.setText("Remover");
        ButaoRemoverAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoRemoverAlimentoActionPerformed(evt);
            }
        });

        ButaoProcurarAlimentoNome.setText("Procurar");
        ButaoProcurarAlimentoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoProcurarAlimentoNomeActionPerformed(evt);
            }
        });

        TXTProcurarNomeAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTProcurarNomeAlimento.setForeground(new java.awt.Color(0, 32, 64));
        TXTProcurarNomeAlimento.setText("Procure Nome");

        TXTProcurarCodigoAlimento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTProcurarCodigoAlimento.setForeground(new java.awt.Color(0, 32, 64));
        TXTProcurarCodigoAlimento.setText("Procurar Código");

        ButaoProcurarCodigoAlimento.setText("Procurar");
        ButaoProcurarCodigoAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoProcurarCodigoAlimentoActionPerformed(evt);
            }
        });

        bntRecarregarLista.setText("Recarregar Lista");
        bntRecarregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRecarregarListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TXTProcurarNomeAlimento)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TXTProcurarCodigoAlimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CapturaTXTProcurarNomeAlimento)
                    .addComponent(CapturaTXTProcurarCodigoAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButaoProcurarAlimentoNome)
                    .addComponent(ButaoProcurarCodigoAlimento))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntRecarregarLista)
                .addGap(116, 116, 116))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CapturaTXTProcurarNomeAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTProcurarNomeAlimento)
                    .addComponent(ButaoProcurarAlimentoNome))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTProcurarCodigoAlimento)
                    .addComponent(CapturaTXTProcurarCodigoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButaoProcurarCodigoAlimento))
                .addGap(18, 18, 18)
                .addComponent(bntRecarregarLista)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ButaoVoltar.setText("Voltar");
        ButaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(ButaoCadastrarAlimento)
                        .addGap(123, 123, 123)
                        .addComponent(ButaoEditarAlimento)
                        .addGap(107, 107, 107)
                        .addComponent(ButaoRemoverAlimento))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTPrecoAlimento)
                                    .addComponent(TXTNomeAlimento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CapturaTXTNomeAlimento, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(CapturaTXTPrecoAlimento)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TXTCodigoAlimento)
                                .addGap(18, 18, 18)
                                .addComponent(CapturaTXTCodigoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButaoVoltar)))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapturaTXTNomeAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTNomeAlimento))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapturaTXTPrecoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTPrecoAlimento))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CapturaTXTCodigoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTCodigoAlimento)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButaoCadastrarAlimento)
                    .addComponent(ButaoEditarAlimento)
                    .addComponent(ButaoRemoverAlimento))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButaoVoltar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CapturaTXTPrecoAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturaTXTPrecoAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapturaTXTPrecoAlimentoActionPerformed

    private void ButaoCadastrarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoCadastrarAlimentoActionPerformed
       if (!validarCampos()) {
            return;
        }
        
        try {
            String nome = CapturaTXTNomeAlimento.getText().trim();
            double preco = Double.parseDouble(CapturaTXTPrecoAlimento.getText().trim());
            int codigo = Integer.parseInt(CapturaTXTCodigoAlimento.getText().trim());
            
            if (bancoDados.tentardicionarAlimento(nome, preco, codigo)) {
                JOptionPane.showMessageDialog(this, "Alimento cadastrado com sucesso!");
                atualizarTabela();
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Erro ao cadastrar. Código já existe ou dados inválidos!", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Preço e código devem ser números válidos!", 
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButaoCadastrarAlimentoActionPerformed

    private void ButaoEditarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoEditarAlimentoActionPerformed
           if (indiceSelecionado == -1) {
        JOptionPane.showMessageDialog(this, 
            "Selecione um alimento na tabela para editar!", 
            "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (!validarCampos()) {
        return;
    }
    
    try {
        int codigoOriginal = (int) modeloTabela.getValueAt(indiceSelecionado, 2);
        String novoNome = CapturaTXTNomeAlimento.getText().trim();
        double novoPreco = Double.parseDouble(CapturaTXTPrecoAlimento.getText().trim());
        int novoCodigo = Integer.parseInt(CapturaTXTCodigoAlimento.getText().trim());
        
        // Substitua esta parte:
        boolean sucesso = true;
        
        // Se está alterando o código
        if (codigoOriginal != novoCodigo) {
            if (!bancoDados.tentarAlterarCodigo(codigoOriginal, novoCodigo)) {
                sucesso = false;
            }
        }
        
        // Altera nome e preço
        if (sucesso) {
            sucesso = bancoDados.tentarAlterarNome(novoCodigo, novoNome) && 
                     bancoDados.tentarAlterarPreco(novoCodigo, novoPreco);
        }
        
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Alimento atualizado com sucesso!");
            atualizarTabela();
            limparCampos();
            indiceSelecionado = -1;
            ButaoCadastrarAlimento.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, 
                "Erro ao atualizar. Verifique se o novo código já existe!", 
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Preço e código devem ser números válidos!", 
            "Erro", JOptionPane.ERROR_MESSAGE);
    }                               
       
        
    }//GEN-LAST:event_ButaoEditarAlimentoActionPerformed

    private void ButaoRemoverAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoRemoverAlimentoActionPerformed
     if (indiceSelecionado == -1) {
            JOptionPane.showMessageDialog(this, 
                "Selecione um alimento na tabela para remover!", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int codigo = (int) modeloTabela.getValueAt(indiceSelecionado, 2);
        String nome = modeloTabela.getValueAt(indiceSelecionado, 0).toString();
        
        int confirmacao = JOptionPane.showConfirmDialog(
            this, 
            "Deseja realmente remover o alimento:\n" + nome + " (Código: " + codigo + ")?", 
            "Confirmar Remoção", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            if (bancoDados.tentarRemoverAlimento(codigo)) {
                JOptionPane.showMessageDialog(this, "Alimento removido com sucesso!");
                atualizarTabela();
                limparCampos();
                indiceSelecionado = -1;
                ButaoCadastrarAlimento.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Erro ao remover alimento!", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ButaoRemoverAlimentoActionPerformed

    private void ButaoProcurarAlimentoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoProcurarAlimentoNomeActionPerformed
       String nomeProcurado = CapturaTXTProcurarNomeAlimento.getText().trim();
        
        if (nomeProcurado.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Digite um nome para procurar!", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        modeloTabela.setRowCount(0);
        Alimento[] resultados = bancoDados.obterAlimentoPorNome(nomeProcurado);
        
        if (resultados.length == 0) {
            JOptionPane.showMessageDialog(this, 
                "Nenhum alimento encontrado com este nome!", 
                "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Alimento alimento : resultados) {
                modeloTabela.addRow(new Object[]{
                    alimento.getNome(),
                    alimento.getPreco(),
                    alimento.getCodigo()
                });
            }
        }
        limparCamposs();
    }//GEN-LAST:event_ButaoProcurarAlimentoNomeActionPerformed

    private void ButaoProcurarCodigoAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoProcurarCodigoAlimentoActionPerformed
        String codigoText = CapturaTXTProcurarCodigoAlimento.getText().trim();
        
        if (codigoText.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Digite um código para procurar!", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int codigo = Integer.parseInt(codigoText);
            Alimento alimento = bancoDados.obterAlimentoPorCodigo(codigo);
            
            if (alimento == null) {
                JOptionPane.showMessageDialog(this, 
                    "Nenhum alimento encontrado com este código!", 
                    "Informação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                modeloTabela.setRowCount(0);
                modeloTabela.addRow(new Object[]{
                    alimento.getNome(),
                    alimento.getPreco(),
                    alimento.getCodigo()
                });
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "O código deve ser um número válido!", 
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
        limparCamposs();
    }//GEN-LAST:event_ButaoProcurarCodigoAlimentoActionPerformed

    private void ButaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoVoltarActionPerformed
        // Chamando a tela Gerente
             Gerente telaGerente = new Gerente("usuario", "senha");
            telaGerente.setVisible(true); // Torna a tela de Gerente visível
            dispose(); // Fecha a tela atual (VendasDeAlimentos)
    }//GEN-LAST:event_ButaoVoltarActionPerformed

    private void bntRecarregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRecarregarListaActionPerformed
    atualizarTabela();  
    limparCampos();  
    }//GEN-LAST:event_bntRecarregarListaActionPerformed

      // ===================== MÉTODOS AUXILIARES ===================== //
    
    private void atualizarTabela() {
        modeloTabela.setRowCount(0);
        Alimento[] alimentos = bancoDados.obterTodosAlimentos();
        for (Alimento alimento : alimentos) {
            modeloTabela.addRow(new Object[]{
                alimento.getNome(),
                alimento.getPreco(),
                alimento.getCodigo()
            });
        }
    }
    
     private void limparCamposs() {
       CapturaTXTProcurarNomeAlimento.setText("");
        CapturaTXTProcurarCodigoAlimento.setText("");
     }
    
    
    
    private void limparCampos() {
        CapturaTXTNomeAlimento.setText("");
        CapturaTXTPrecoAlimento.setText("");
        CapturaTXTCodigoAlimento.setText("");
        CapturaTXTProcurarNomeAlimento.setText("");
        CapturaTXTProcurarCodigoAlimento.setText("");
    }
    
    private boolean validarCampos() {
        if (CapturaTXTNomeAlimento.getText().trim().isEmpty() ||
            CapturaTXTPrecoAlimento.getText().trim().isEmpty() ||
            CapturaTXTCodigoAlimento.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, 
                "Preencha todos os campos obrigatórios!", 
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        try {
            double preco = Double.parseDouble(CapturaTXTPrecoAlimento.getText().trim());
            if (preco <= 0) {
                JOptionPane.showMessageDialog(this, 
                    "O preço deve ser maior que zero!", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "O preço deve ser um número válido!", 
                "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try {
            Integer.parseInt(CapturaTXTCodigoAlimento.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "O código deve ser um número válido!", 
                "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButaoCadastrarAlimento;
    private javax.swing.JButton ButaoEditarAlimento;
    private javax.swing.JButton ButaoProcurarAlimentoNome;
    private javax.swing.JButton ButaoProcurarCodigoAlimento;
    private javax.swing.JButton ButaoRemoverAlimento;
    private javax.swing.JButton ButaoVoltar;
    private javax.swing.JTextField CapturaTXTCodigoAlimento;
    private javax.swing.JTextField CapturaTXTNomeAlimento;
    private javax.swing.JTextField CapturaTXTPrecoAlimento;
    private javax.swing.JTextField CapturaTXTProcurarCodigoAlimento;
    private javax.swing.JTextField CapturaTXTProcurarNomeAlimento;
    private javax.swing.JTable PlanilhaAlimento;
    private javax.swing.JLabel TXTCodigoAlimento;
    private javax.swing.JLabel TXTGenrenciAlimentos;
    private javax.swing.JLabel TXTNomeAlimento;
    private javax.swing.JLabel TXTPrecoAlimento;
    private javax.swing.JLabel TXTProcurarCodigoAlimento;
    private javax.swing.JLabel TXTProcurarNomeAlimento;
    private javax.swing.JButton bntRecarregarLista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
