
package cinemax.frontend.alimentos;

import cinemax.backend.alimentos.Alimento;
import cinemax.frontend.controller.ControladorDeApp;
import cinemax.frontend.estilizacao.Estilizador;
import cinemax.frontend.estilizacao.EstiloBotao;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.Map;
import java.util.HashMap;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

public class TelaCarrinhoAlimentos extends javax.swing.JFrame {
	private DefaultTableModel modeloTabela;
	private ControladorDeApp app = ControladorDeApp.getInstancia();
	private TelaVendaDeAlimento vendaDeAlimento;

	/**
	 * Creates new form CarrinhoDeComprasAlimentos
	 */
	public TelaCarrinhoAlimentos(TelaVendaDeAlimento vendaDeAlimento) {
		initComponents();
		configurarTabela();
		this.vendaDeAlimento = vendaDeAlimento;
	}

	private void configurarTabela() {
		modeloTabela = (DefaultTableModel) TabelaCarrinho.getModel();
		modeloTabela.setColumnIdentifiers(new String[] { "Item", "Preço", "Quantidade", "Subtotal" });
		Color corFundoCabelho =  new Color(2, 17, 28);
        Estilizador.estilizarTabela(TabelaCarrinho,corFundoCabelho);
	}

	public void adicionarItens(Map<Alimento, Integer> itens) {
		modeloTabela.setRowCount(0);
		double total = 0;

		for (Map.Entry<Alimento, Integer> entry : itens.entrySet()) {
			Alimento alimento = entry.getKey();
			int quantidade = entry.getValue();
			double subtotal = alimento.getPreco() * quantidade;
			total += subtotal;

			modeloTabela.addRow(new Object[] { alimento.getNome(), String.format("R$ %.2f", alimento.getPreco()),
					quantidade, String.format("R$ %.2f", subtotal) });
		}

		TXTTotal.setText("Total de Compra: R$ " + String.format("%.2f", total));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		contentPane = new javax.swing.JPanel();
		jPanePrincipal = new javax.swing.JPanel();
		jScrollPaneTabela = new javax.swing.JScrollPane();
		TabelaCarrinho = new javax.swing.JTable();
		jPanelTotalCompra = new javax.swing.JPanel();
		jLabelTotalCompra = new javax.swing.JLabel();
		jLabelTotalCompra.setFont(new Font("Tahoma", Font.BOLD, 13));
		TXTTotal = new javax.swing.JLabel();

		jPanePrincipal = Estilizador.criarPainelArredondado(new Color(255, 255, 255), 10);
		jPanelTotalCompra = Estilizador.criarPainelArredondadoComBorda(new Color(200, 200, 200),Color.BLACK, 10,1);


		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(2, 32, 64));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		contentPane.setBackground(new Color(2, 17, 28));

		TabelaCarrinho
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Item", "Preço", "Quantidade", "Subtotal" }));
		jScrollPaneTabela.setViewportView(TabelaCarrinho);

		TXTTotal.setText("Total da compra: R$ 0.00");
		TXTTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		TXTTotal.setHorizontalAlignment(SwingConstants.CENTER);


		javax.swing.GroupLayout gl_jPanelTotalCompra = new javax.swing.GroupLayout(jPanelTotalCompra);
		gl_jPanelTotalCompra.setHorizontalGroup(
			gl_jPanelTotalCompra.createParallelGroup(Alignment.TRAILING)
				.addComponent(jLabelTotalCompra, GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
				.addComponent(TXTTotal, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
		);
		gl_jPanelTotalCompra.setVerticalGroup(
			gl_jPanelTotalCompra.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanelTotalCompra.createSequentialGroup()
					.addGap(15)
					.addGroup(gl_jPanelTotalCompra.createParallelGroup(Alignment.BASELINE)
						.addComponent(jLabelTotalCompra)
						.addComponent(TXTTotal))
					.addContainerGap(15, Short.MAX_VALUE))
		);
		jPanelTotalCompra.setLayout(gl_jPanelTotalCompra);

		javax.swing.GroupLayout gl_jPanePrincipal = new javax.swing.GroupLayout(jPanePrincipal);
		gl_jPanePrincipal.setHorizontalGroup(
			gl_jPanePrincipal.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanePrincipal.createSequentialGroup()
					.addGroup(gl_jPanePrincipal.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_jPanePrincipal.createSequentialGroup()
							.addGap(40)
							.addComponent(jScrollPaneTabela, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGroup(gl_jPanePrincipal.createSequentialGroup()
							.addGap(99)
							.addComponent(jPanelTotalCompra, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(42, Short.MAX_VALUE))
		);
		gl_jPanePrincipal.setVerticalGroup(
			gl_jPanePrincipal.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_jPanePrincipal.createSequentialGroup()
					.addGap(22)
					.addComponent(jScrollPaneTabela, GroupLayout.PREFERRED_SIZE, 375, GroupLayout.PREFERRED_SIZE)
					.addGap(26)
					.addComponent(jPanelTotalCompra, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
					.addGap(35))
		);
		jPanePrincipal.setLayout(gl_jPanePrincipal);
		bntComprar = new javax.swing.JButton();
		bntComprar.setFont(new Font("Tahoma", Font.BOLD, 13));

		bntComprar.setText("Concluir compra");
		bntComprar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ComprarActionPerformed(evt);
			}
		});
		bntVoltar = new javax.swing.JButton();
		bntVoltar.setFont(new Font("Tahoma", Font.BOLD, 13));

		bntVoltar.setText("  Voltar  ");
		bntVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				VoltarActionPerformed(evt);
			}
		});
		
		Estilizador.aplicarEstiloBotao(bntVoltar, EstiloBotao.CLARO_UNIFICADO);
        
        Estilizador.aplicarEstiloBotao(bntComprar, EstiloBotao.CLARO_UNIFICADO);

		javax.swing.GroupLayout gl_contentPane = new javax.swing.GroupLayout(contentPane);
		gl_contentPane.setHorizontalGroup(
			gl_contentPane.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(19)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.TRAILING, false)
						.addGroup(gl_contentPane.createSequentialGroup()
							.addComponent(bntVoltar)
							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(bntComprar))
						.addComponent(jPanePrincipal, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 534, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(21, Short.MAX_VALUE))
		);
		gl_contentPane.setVerticalGroup(
			gl_contentPane.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_contentPane.createSequentialGroup()
					.addGap(24)
					.addComponent(jPanePrincipal, GroupLayout.PREFERRED_SIZE, 508, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
					.addGroup(gl_contentPane.createParallelGroup(Alignment.BASELINE)
						.addComponent(bntComprar)
						.addComponent(bntVoltar))
					.addGap(19))
		);
		contentPane.setLayout(gl_contentPane);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VoltarActionPerformed
		dispose();
	}// GEN-LAST:event_VoltarActionPerformed

	private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ComprarActionPerformed

		int confirm = JOptionPane.showConfirmDialog(this, "Confirmar compra no valor de " + TXTTotal.getText() + "?",
				"Confirmação de Compra", JOptionPane.YES_NO_OPTION);

		if (confirm == JOptionPane.YES_OPTION) {
			try {

				if (modeloTabela.getRowCount() == 0) {
					JOptionPane.showMessageDialog(this, "Nenhum item no carrinho.", "Erro", JOptionPane.ERROR_MESSAGE);
					return;
				}

				Map<Alimento, Integer> itens = new HashMap<>();
				for (int i = 0; i < modeloTabela.getRowCount(); i++) {
					String nome = (String) modeloTabela.getValueAt(i, 0);
					String precoString = (String) modeloTabela.getValueAt(i, 1);

					precoString = precoString.replace("R$ ", "").replace(",", ".");
					double preco = Double.parseDouble(precoString);

					int quantidade = (Integer) modeloTabela.getValueAt(i, 2);

					Alimento alimento = new Alimento(nome, preco, 0);
					itens.put(alimento, quantidade);
				}

				if (app.getBackend().getGerenciadorRelatorios().obterRelatorioDoDia().getRelatorioAlimentos()
						.adicionarVendas(itens)) {
					JOptionPane.showMessageDialog(null, "Compra registrada com sucesso!", "Sucesso",
							JOptionPane.INFORMATION_MESSAGE);

					modeloTabela.setRowCount(0);
					TXTTotal.setText("0");

					this.vendaDeAlimento.limparCamposs();
					this.vendaDeAlimento.toFront();
					
					this.dispose();

					/*for (Window window : Window.getWindows()) {
						if (window instanceof TelaVendaDeAlimento) {
							TelaVendaDeAlimento telaVenda = (TelaVendaDeAlimento) window;
							telaVenda.limparCamposs();
							telaVenda.toFront();
							break;
						}
					}*/
				} else {
					JOptionPane.showMessageDialog(this, "Não é permitido vendas ainda", "Erro", JOptionPane.ERROR_MESSAGE);
				}


			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "Erro ao processar compra: " + e.getMessage(), "Erro",
						JOptionPane.ERROR_MESSAGE);
			}
		}
	}// GEN-LAST:event_ComprarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaCarrinhoAlimentos.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaCarrinhoAlimentos.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaCarrinhoAlimentos.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaCarrinhoAlimentos.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaCarrinhoAlimentos(null).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton bntComprar;
	private javax.swing.JLabel TXTTotal;
	private javax.swing.JTable TabelaCarrinho;
	private javax.swing.JButton bntVoltar;
	private javax.swing.JLabel jLabelTotalCompra;
	private javax.swing.JPanel contentPane;
	private javax.swing.JPanel jPanePrincipal;
	private javax.swing.JPanel jPanelTotalCompra;
	private javax.swing.JScrollPane jScrollPaneTabela;
	// End of variables declaration//GEN-END:variables
}
