/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemax.frontend.PaginasGeranteeFuncionario;

import cinemax.frontend.RelatorioGeral.TelaRelatorioFinal;
import cinemax.frontend.controller.ControladorDeApp;
import cinemax.frontend.geranciadefuncionarios.Gerencia;
import cinemax.frontend.gerenciamentofilmes.TelaCrudFilme;
import cinemax.frontend.vendadealimentos.Vendas;
import cinemax.frontend.vendadealimentos.VendaDealimentoss;
import cinemax.frontend.vendadeingressos.TelaEscolhaFilme;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.Font;


/**
 *
 * @author geral
 */
public class Gerente extends javax.swing.JFrame {

	private ControladorDeApp app = ControladorDeApp.getInstancia();
	
	
    /**
     * Creates new form Gerente
     */
    public Gerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotaoAcessarGeranciaFuncinario = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botaoIniciarDia = new javax.swing.JButton();
        JButton BotaoAcessarGeranciaDeFilmes = new JButton();
        BotaoAcessarGeranciaDeFilmes.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		TelaCrudFilme telaCrudFilme = new TelaCrudFilme();
        	    telaCrudFilme.setLocationRelativeTo(null);
        	    telaCrudFilme.setVisible(true);
        	    
        	    dispose(); // Fecha a tela atual se quiser
        	}
        });
        botaoIniciarDia.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		app.getBackend().tentarAbrirDia();
        		botaoIniciarDia.setEnabled(false);
        		
        		botaoTerminoDia.setEnabled(true);
                BotaoAcessarVendaDeAlimentos.setEnabled(true);
                botaoAcessoCompraDeIngresos.setEnabled(true);
                
                BotaoAcessarGeranciaFuncinario.setEnabled(false);
        		BotaoAcessarGeranciaDeFilmes.setEnabled(false);
                BotaoAcessarGeranciaDeAlimentos.setEnabled(false);
                
        	}
        });
        
        botaoTerminoDia = new javax.swing.JButton();
        botaoTerminoDia.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		app.getBackend().tentarFecharDia();
        		botaoTerminoDia.setEnabled(false);
        		
        		BotaoAcessarGeranciaFuncinario.setEnabled(true);
        		BotaoAcessarGeranciaDeFilmes.setEnabled(true);
                BotaoAcessarGeranciaDeAlimentos.setEnabled(true);
                
                botaoConsultarRelatorio.setEnabled(true);
                BotaoAcessarVendaDeAlimentos.setEnabled(false);
                botaoAcessoCompraDeIngresos.setEnabled(false);
                
        	}
        });
        botaoConsultarRelatorio = new javax.swing.JButton();
        botaoConsultarRelatorio.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		TelaRelatorioFinal telaRelatorioFinal = new TelaRelatorioFinal();
        		telaRelatorioFinal.setVisible(true);
        		telaRelatorioFinal.setLocationRelativeTo(null);
        		
        		dispose();
        	}
        });
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        TXTVendaDeAlimentos = new javax.swing.JLabel();
        BotaoAcessarVendaDeAlimentos = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botaoAcessoCompraDeIngresos = new javax.swing.JButton();
        botaoAcessoCompraDeIngresos.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		TelaEscolhaFilme telaEscolhaFilme = new TelaEscolhaFilme();
            	telaEscolhaFilme.setLocationRelativeTo(null);
            	telaEscolhaFilme.setVisible(true);
            	
            	dispose();
        	}
        	
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(2, 32, 64));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seção de Gerenciamento de Fucionários");

        BotaoAcessarGeranciaFuncinario.setText("Acessar");
        if(!app.getBackend().diaEstaAberto()) BotaoAcessarGeranciaFuncinario.setEnabled(true);
        else BotaoAcessarGeranciaFuncinario.setEnabled(false);
        BotaoAcessarGeranciaFuncinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButaoAcessarGeranciaDeFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(BotaoAcessarGeranciaFuncinario)
        			.addGap(124))
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2)
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(27)
        					.addComponent(BotaoAcessarGeranciaFuncinario))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel3.setBackground(new java.awt.Color(2, 32, 64));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Consultar relatório de vendas:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Inicio da Operações do dia:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Término das Operações do dia:");

        botaoIniciarDia.setText("Iniciar");

        botaoTerminoDia.setText("Termino");
        if(!app.getBackend().diaEstaAberto())botaoTerminoDia.setEnabled(false);
        else botaoTerminoDia.setEnabled(true);

        botaoConsultarRelatorio.setText("Consulatar relatório");
        botaoConsultarRelatorio.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(185)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(botaoIniciarDia)
        					.addGap(45))
        				.addComponent(jLabel6))
        			.addPreferredGap(ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel8)
        					.addGap(156))
        				.addGroup(Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        					.addComponent(botaoTerminoDia)
        					.addGap(207)))
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel5)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGap(24)
        					.addComponent(botaoConsultarRelatorio)))
        			.addGap(179))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGap(19)
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(jLabel5)
        							.addGap(18)
        							.addComponent(botaoConsultarRelatorio))
        						.addGroup(jPanel3Layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(18)
        							.addComponent(botaoIniciarDia))))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel8)
        					.addGap(18)
        					.addComponent(botaoTerminoDia)))
        			.addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel3.setLayout(jPanel3Layout);

        jPanel5.setBackground(new java.awt.Color(2, 32, 64));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bem-Vindo a Área do Gerente");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        			.addContainerGap(478, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addGap(473))
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
        			.addContainerGap(18, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addContainerGap())
        );
        jPanel5.setLayout(jPanel5Layout);

        jPanel8.setBackground(new java.awt.Color(2, 32, 64));

        TXTVendaDeAlimentos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTVendaDeAlimentos.setForeground(new java.awt.Color(255, 255, 255));
        TXTVendaDeAlimentos.setText("Venda de Alimentos");

        BotaoAcessarVendaDeAlimentos.setText("Acessar");
        if(!app.getBackend().diaEstaAberto()) BotaoAcessarVendaDeAlimentos.setEnabled(false);
        else BotaoAcessarVendaDeAlimentos.setEnabled(true);
        BotaoAcessarVendaDeAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVendaDealimentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(BotaoAcessarVendaDeAlimentos))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(TXTVendaDeAlimentos)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TXTVendaDeAlimentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoAcessarVendaDeAlimentos))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(2, 32, 64));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Venda de ingressos");

        botaoAcessoCompraDeIngresos.setText("Acessar");
        if(!app.getBackend().diaEstaAberto()) botaoAcessoCompraDeIngresos.setEnabled(false);
        else botaoAcessoCompraDeIngresos.setEnabled(true);
        

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(botaoAcessoCompraDeIngresos))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAcessoCompraDeIngresos))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        JPanel jPanel2_1 = new JPanel();
        jPanel2_1.setBackground(new Color(2, 32, 64));
        
        JPanel jPanel6_1 = new JPanel();
        GroupLayout gl_jPanel6_1 = new GroupLayout(jPanel6_1);
        gl_jPanel6_1.setHorizontalGroup(
        	gl_jPanel6_1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 100, Short.MAX_VALUE)
        		.addGap(0, 100, Short.MAX_VALUE)
        );
        gl_jPanel6_1.setVerticalGroup(
        	gl_jPanel6_1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 100, Short.MAX_VALUE)
        		.addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6_1.setLayout(gl_jPanel6_1);
        
       
        BotaoAcessarGeranciaDeFilmes.setText("Acessar");
        if(!app.getBackend().diaEstaAberto()) BotaoAcessarGeranciaDeFilmes.setEnabled(true);
        else BotaoAcessarGeranciaDeFilmes.setEnabled(false);
        
        JLabel jLabel2_1 = new JLabel();
        jLabel2_1.setText("Seção de Gerenciamento de Filmes");
        jLabel2_1.setForeground(Color.WHITE);
        jLabel2_1.setFont(new Font("Segoe UI", Font.BOLD, 12));
        GroupLayout gl_jPanel2_1 = new GroupLayout(jPanel2_1);
        gl_jPanel2_1.setHorizontalGroup(
        	gl_jPanel2_1.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 228, Short.MAX_VALUE)
        		.addGroup(gl_jPanel2_1.createSequentialGroup()
        			.addContainerGap(14, Short.MAX_VALUE)
        			.addComponent(jPanel6_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(BotaoAcessarGeranciaDeFilmes)
        			.addGap(124))
        		.addGroup(Alignment.LEADING, gl_jPanel2_1.createSequentialGroup()
        			.addGap(22)
        			.addComponent(jLabel2_1)
        			.addContainerGap(109, Short.MAX_VALUE))
        );
        gl_jPanel2_1.setVerticalGroup(
        	gl_jPanel2_1.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 194, Short.MAX_VALUE)
        		.addGroup(gl_jPanel2_1.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel2_1)
        			.addGap(18)
        			.addGroup(gl_jPanel2_1.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel2_1.createSequentialGroup()
        					.addGap(27)
        					.addComponent(BotaoAcessarGeranciaDeFilmes))
        				.addGroup(gl_jPanel2_1.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jPanel6_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2_1.setLayout(gl_jPanel2_1);
        
        jPanel2_2 = new JPanel();
        jPanel2_2.setBackground(new Color(2, 32, 64));
        
        jPanel6_2 = new JPanel();
        GroupLayout gl_jPanel6_2 = new GroupLayout(jPanel6_2);
        gl_jPanel6_2.setHorizontalGroup(
        	gl_jPanel6_2.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 100, Short.MAX_VALUE)
        		.addGap(0, 100, Short.MAX_VALUE)
        );
        gl_jPanel6_2.setVerticalGroup(
        	gl_jPanel6_2.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 100, Short.MAX_VALUE)
        		.addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6_2.setLayout(gl_jPanel6_2);
        BotaoAcessarGeranciaDeAlimentos = new javax.swing.JButton();
        
                BotaoAcessarGeranciaDeAlimentos.setText("Acessar");
                if(!app.getBackend().diaEstaAberto()) BotaoAcessarGeranciaDeAlimentos.setEnabled(true);
                else BotaoAcessarGeranciaDeAlimentos.setEnabled(false);
                BotaoAcessarGeranciaDeAlimentos.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ButaoAcessarGeranciaDeAlimentosActionPerformed(evt);
                    }
                });
        
        jLabel4 = new JLabel();
        jLabel4.setText("Seção Gerência de vendas de Alimentos");
        jLabel4.setForeground(Color.WHITE);
        jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 12));
        GroupLayout gl_jPanel2_2 = new GroupLayout(jPanel2_2);
        gl_jPanel2_2.setHorizontalGroup(
        	gl_jPanel2_2.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel2_2.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(jPanel6_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(BotaoAcessarGeranciaDeAlimentos)
        			.addGap(116))
        		.addGroup(gl_jPanel2_2.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 221, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(84, Short.MAX_VALUE))
        );
        gl_jPanel2_2.setVerticalGroup(
        	gl_jPanel2_2.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel2_2.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_jPanel2_2.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel2_2.createSequentialGroup()
        					.addGap(36)
        					.addComponent(jPanel6_2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(gl_jPanel2_2.createSequentialGroup()
        					.addGap(46)
        					.addComponent(BotaoAcessarGeranciaDeAlimentos)))
        			.addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2_2.setLayout(gl_jPanel2_2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(36)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addGap(98)
        					.addComponent(jPanel2_1, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
        					.addGap(116)
        					.addComponent(jPanel2_2, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
        					.addGap(124))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(41)
        					.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(328)
        					.addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, 365, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPanel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        				.addComponent(jPanel2_2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        				.addComponent(jPanel2_1, GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel10, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(35)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(43))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButaoAcessarGeranciaDeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoAcessarGeranciaDeFuncionarioActionPerformed
    Gerencia gerencia = new Gerencia();
    gerencia.setLocationRelativeTo(null);
    gerencia.setVisible(true);
    this.dispose(); // Fecha a tela atual se quiser
    }//GEN-LAST:event_ButaoAcessarGeranciaDeFuncionarioActionPerformed

    private void ButaoAcessarGeranciaDeAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButaoAcessarGeranciaDeAlimentosActionPerformed
    Vendas gerenciamento = new Vendas();
    gerenciamento.setLocationRelativeTo(null);
    gerenciamento.setVisible(true);  // Torna a janela Vendas visível
    this.dispose();  // Fecha a janela atual
    }//GEN-LAST:event_ButaoAcessarGeranciaDeAlimentosActionPerformed

    private void BotaoVendaDealimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVendaDealimentosActionPerformed
    VendaDealimentoss vendas = new VendaDealimentoss();
    vendas.setLocationRelativeTo(null); 
    vendas.setVisible(true);  // Torna a janela Vendas visível
    this.dispose();  // Fecha a janela atual
    }//GEN-LAST:event_BotaoVendaDealimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Gerente telaGerente = new Gerente();
    			telaGerente.setVisible(true);
    			telaGerente.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BotaoAcessarVendaDeAlimentos;
    private javax.swing.JButton BotaoAcessarGeranciaDeAlimentos;
    private javax.swing.JButton BotaoAcessarGeranciaFuncinario;
    private javax.swing.JLabel TXTVendaDeAlimentos;
    private javax.swing.JButton botaoAcessoCompraDeIngresos;
    private javax.swing.JButton botaoConsultarRelatorio;
    private javax.swing.JButton botaoIniciarDia;
    private javax.swing.JButton botaoTerminoDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private JPanel jPanel2_2;
    private JPanel jPanel6_2;
    private JLabel jLabel4;
}
