/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemax.frontend.PaginasGeranteeFuncionario;

import cinemax.frontend.controller.ControladorDeApp;
import cinemax.frontend.login.TelaLogin;
import cinemax.frontend.vendadealimentos.TelaVendaDeAlimento;
import cinemax.frontend.vendadeingressos.TelaVendaDeIngresso;

import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import java.awt.Color;

/**
 *
 * @author geral
 */
public class TelaFuncionario extends javax.swing.JFrame {

	/**
	 * Creates new form Funcionarios
	 */
	public TelaFuncionario() {
		getContentPane().setBackground(new Color(2, 18, 27));
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		BotaoAcessarVendaDeAlimentos = new javax.swing.JButton();
		BotaoAcessarVendaDeAlimentos.setFont(new Font("Tahoma", Font.BOLD, 12));
		jLabel2 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		BotaoVendasDeIngressos = new javax.swing.JButton();
		BotaoVendasDeIngressos.setFont(new Font("Tahoma", Font.BOLD, 12));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Cinemax");

		jPanel1.setBackground(new Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(0, 0, 0));
		jLabel1.setText("Área do funcionário");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(351, 351, 351).addComponent(jLabel1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addContainerGap(16, Short.MAX_VALUE)));

		jPanel2.setBackground(new Color(255, 255, 255));

		BotaoAcessarVendaDeAlimentos.setText("Acessar");
		BotaoAcessarVendaDeAlimentos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoAcessarVendaDeAlimentosActionPerformed(evt);
			}
		});
		BotaoAcessarVendaDeAlimentos.setEnabled(
				ControladorDeApp.getInstancia().getBackend().diaEstaAberto());

		jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 0, 0));
		jLabel2.setText("Vendas de Alimentos");
		
		ImageIcon iconeVendaDeIngressoParcial = new ImageIcon(getClass().getResource("/img/VendaDeIngresso.png"));
    	Image imgIconeVendaDeIngressoParcial = iconeVendaDeIngressoParcial.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
    	ImageIcon iconeVendaDeIngresso = new ImageIcon(imgIconeVendaDeIngressoParcial);
		
		lblVendaDeIngresso = new JLabel(iconeVendaDeIngresso);
		
		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblVendaDeIngresso, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
							.addComponent(jLabel2)
							.addGap(66))
						.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
							.addComponent(BotaoAcessarVendaDeAlimentos)
							.addGap(85))))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addGap(63)
							.addComponent(jLabel2)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(BotaoAcessarVendaDeAlimentos))
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addGap(38)
							.addComponent(lblVendaDeIngresso, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(28, Short.MAX_VALUE))
		);
		jPanel2.setLayout(jPanel2Layout);

		jPanel3.setBackground(new Color(255, 255, 255));

		jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 0, 0));
		jLabel3.setText("Vendas de Ingressos");

		BotaoVendasDeIngressos.setText("Acessar");
		BotaoVendasDeIngressos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoVendasDeIngressosActionPerformed(evt);
			}
		});
		BotaoVendasDeIngressos.setEnabled(
			ControladorDeApp.getInstancia().getBackend().diaEstaAberto());
		
		ImageIcon iconeVendaDeAlimentoParcial = new ImageIcon(getClass().getResource("/img/VendaDeAlimento.png"));
    	Image imgIconeVendaDeAlimentoParcial = iconeVendaDeAlimentoParcial.getImage().getScaledInstance(100, 60, Image.SCALE_SMOOTH);
    	ImageIcon iconeVendaDeAlimento = new ImageIcon(imgIconeVendaDeAlimentoParcial);
		
		lblVendaDeAlimento = new JLabel(iconeVendaDeAlimento);
		
		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblVendaDeAlimento, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addComponent(jLabel3)
							.addGap(77))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addComponent(BotaoVendasDeIngressos)
							.addGap(92))))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap(59, Short.MAX_VALUE)
					.addComponent(jLabel3)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(BotaoVendasDeIngressos)
					.addGap(74))
				.addGroup(Alignment.LEADING, jPanel3Layout.createSequentialGroup()
					.addGap(27)
					.addComponent(lblVendaDeAlimento, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(40, Short.MAX_VALUE))
		);
		jPanel3.setLayout(jPanel3Layout);
		
		btnVoltar = new JButton("Voltar");
		btnVoltar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				TelaLogin loginDeAcesso = new TelaLogin();
				loginDeAcesso.setVisible(true);
				loginDeAcesso.setLocationRelativeTo(null);
				
				dispose();
			}
		});
		btnVoltar.setFont(new Font("Tahoma", Font.BOLD, 13));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
					.addGap(90)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(40)
					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(131, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup()
					.addGap(22)
					.addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(837, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(138)
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addGap(154)
					.addComponent(btnVoltar)
					.addContainerGap(21, Short.MAX_VALUE))
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void BotaoVendasDeIngressosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotaoVendasDeIngressosActionPerformed
		TelaVendaDeIngresso telaEscolhaFilme = new TelaVendaDeIngresso();
		telaEscolhaFilme.setLocationRelativeTo(null);
		telaEscolhaFilme.setVisible(true); // Torna a janela Vendas visível
		this.dispose();
	}// GEN-LAST:event_BotaoVendasDeIngressosActionPerformed

	private void BotaoAcessarVendaDeAlimentosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotaoAcessarVendaDeAlimentosActionPerformed
		TelaVendaDeAlimento vendass = new TelaVendaDeAlimento();
		vendass.setLocationRelativeTo(null);
		vendass.setVisible(true); // Torna a janela Vendas visível
		this.dispose();
	}// GEN-LAST:event_BotaoAcessarVendaDeAlimentosActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaFuncionario().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton BotaoAcessarVendaDeAlimentos;
	private javax.swing.JButton BotaoVendasDeIngressos;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private JButton btnVoltar;
	private JLabel lblVendaDeIngresso;
	private JLabel lblVendaDeAlimento;
	// End of variables declaration//GEN-END:variables
}
