/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinemax.frontend.PaginasGeranteeFuncionario;

import cinemax.frontend.RelatorioGeral.TelaEscolhaRelatorio;
import cinemax.frontend.alimentos.TelaCrudAlimento;
import cinemax.frontend.alimentos.TelaVendaDeAlimento;
import cinemax.backend.core.Backend;
import cinemax.backend.funcionarios.BancoDeDadosFuncionario;
import cinemax.backend.funcionarios.IBancoDeDadosFuncionario;
import cinemax.frontend.controller.ControladorDeApp;
import cinemax.frontend.estilizacao.Estilizador;
import cinemax.frontend.estilizacao.EstiloBotao;
import cinemax.frontend.geranciadefuncionarios.TelaCrudFuncionario;
import cinemax.frontend.gerenciamentofilmes.TelaCrudFilme;
import cinemax.frontend.login.TelaLogin;
import cinemax.frontend.vendadeingressos.TelaVendaDeIngresso;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Image;

/**
 *
 * @author Geraldo
 */
@SuppressWarnings("serial")
public class TelaGerente extends javax.swing.JFrame {

	private ControladorDeApp app = ControladorDeApp.getInstancia();
	
	/**
	 * Creates new form Gerente
	 */
	public TelaGerente() {
		initComponents();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new Color(2, 18, 27));
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotaoAcessarGeranciaFuncinario = new javax.swing.JButton();
        Estilizador.aplicarEstiloBotao(BotaoAcessarGeranciaFuncinario, EstiloBotao.PADRAO_ESCURECIDO);
        BotaoAcessarGeranciaFuncinario.setFont(new Font("Tahoma", Font.BOLD, 11));
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botaoIniciarDia = new javax.swing.JButton();
        Estilizador.aplicarEstiloBotao(botaoIniciarDia, EstiloBotao.PADRAO_ESCURECIDO);
        botaoIniciarDia.setFont(new Font("Tahoma", Font.BOLD, 12));
        JButton BotaoAcessarGeranciaDeFilmes = new JButton();
        Estilizador.aplicarEstiloBotao(BotaoAcessarGeranciaDeFilmes, EstiloBotao.PADRAO_ESCURECIDO);
        BotaoAcessarGeranciaDeFilmes.setFont(new Font("Tahoma", Font.BOLD, 12));
        BotaoAcessarGeranciaDeFilmes.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		TelaCrudFilme telaCrudFilme = new TelaCrudFilme();
        	    telaCrudFilme.setLocationRelativeTo(null);
        	    telaCrudFilme.setVisible(true);
        	    
        	    dispose(); // Fecha a tela atual se quiser
        	}
        });
        botaoIniciarDia.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		app.getBackend().tentarAbrirDia();
        		botaoIniciarDia.setEnabled(false);
        		
        		botaoTerminoDia.setEnabled(true);
                BotaoAcessarVendaDeAlimentos.setEnabled(true);
                botaoAcessoCompraDeIngresos.setEnabled(true);
                
                BotaoAcessarGeranciaFuncinario.setEnabled(false);
        		BotaoAcessarGeranciaDeFilmes.setEnabled(false);
                BotaoAcessarGeranciaDeAlimentos.setEnabled(false);
                botaoConsultarRelatorio.setEnabled(false);
        	}
        });
        if(app.getBackend().diaEstaAberto()) {
        	botaoIniciarDia.setEnabled(false);
        }
        
        botaoTerminoDia = new javax.swing.JButton();
        Estilizador.aplicarEstiloBotao(botaoTerminoDia, EstiloBotao.PADRAO_ESCURECIDO);
        botaoTerminoDia.setFont(new Font("Tahoma", Font.BOLD, 12));
        botaoTerminoDia.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		app.getBackend().tentarFecharDia();
        		botaoTerminoDia.setEnabled(false);
        		botaoIniciarDia.setEnabled(true);
        		
        		BotaoAcessarGeranciaFuncinario.setEnabled(true);
        		BotaoAcessarGeranciaDeFilmes.setEnabled(true);
                BotaoAcessarGeranciaDeAlimentos.setEnabled(true);
                
                botaoConsultarRelatorio.setEnabled(true);
                BotaoAcessarVendaDeAlimentos.setEnabled(false);
                botaoAcessoCompraDeIngresos.setEnabled(false);
                
        	}
        });
        if(!app.getBackend().diaEstaAberto()) {
        	botaoTerminoDia.setEnabled(false);
        }
        botaoConsultarRelatorio = new javax.swing.JButton();
        Estilizador.aplicarEstiloBotao(botaoConsultarRelatorio, EstiloBotao.PADRAO_ESCURECIDO);
        botaoConsultarRelatorio.setFont(new Font("Tahoma", Font.BOLD, 12));
        botaoConsultarRelatorio.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		TelaEscolhaRelatorio telaEscolhaRelatorio = new TelaEscolhaRelatorio();
        		telaEscolhaRelatorio.setVisible(true);
        		telaEscolhaRelatorio.setLocationRelativeTo(null);
        		
        		dispose();
        	}
        });
        if(app.getBackend().getGerenciadorRelatorios().size() > 0 && !app.getBackend().diaEstaAberto()) {
        	botaoConsultarRelatorio.setEnabled(true);
        } else {
        	botaoConsultarRelatorio.setEnabled(false);
        }
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        TXTVendaDeAlimentos = new javax.swing.JLabel();
        BotaoAcessarVendaDeAlimentos = new javax.swing.JButton();
        Estilizador.aplicarEstiloBotao(BotaoAcessarVendaDeAlimentos, EstiloBotao.PADRAO_ESCURECIDO);
        BotaoAcessarVendaDeAlimentos.setFont(new Font("Tahoma", Font.BOLD, 12));
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botaoAcessoCompraDeIngresos = new javax.swing.JButton();
        Estilizador.aplicarEstiloBotao(botaoAcessoCompraDeIngresos, EstiloBotao.PADRAO_ESCURECIDO);
        botaoAcessoCompraDeIngresos.setFont(new Font("Tahoma", Font.BOLD, 12));
        botaoAcessoCompraDeIngresos.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		TelaVendaDeIngresso telaEscolhaFilme = new TelaVendaDeIngresso();
            	telaEscolhaFilme.setLocationRelativeTo(null);
            	telaEscolhaFilme.setVisible(true);
            	
            	dispose();
        	}
        	
        });

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Cinemax");

		jPanel2.setBackground(new Color(255, 255, 255));

		jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(0, 0, 0));
		jLabel2.setText("Seção de Gerenciamento de Fucionários");

		BotaoAcessarGeranciaFuncinario.setText("Acessar");
		if (!app.getBackend().diaEstaAberto())
			BotaoAcessarGeranciaFuncinario.setEnabled(true);
		else
			BotaoAcessarGeranciaFuncinario.setEnabled(false);
		BotaoAcessarGeranciaFuncinario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButaoAcessarGeranciaDeFuncionarioActionPerformed(evt);
			}
		});
		
		ImageIcon iconeGerenciamentoDeFuncionarioParcial = new ImageIcon(getClass().getResource("/img/GerenciamentoDeFuncionario.png"));
    	Image imgIconeGerenciamentoDeFuncionarioParcial = iconeGerenciamentoDeFuncionarioParcial.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
    	ImageIcon iconeGerenciamentoDeFuncionario = new ImageIcon(imgIconeGerenciamentoDeFuncionarioParcial);
		lblGerenciamentoDeFuncionario = new JLabel(iconeGerenciamentoDeFuncionario);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblGerenciamentoDeFuncionario, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(BotaoAcessarGeranciaFuncinario)
					.addGap(50))
				.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(jLabel2)
					.addContainerGap())
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel2)
					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(lblGerenciamentoDeFuncionario, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel2Layout.createSequentialGroup()
							.addGap(51)
							.addComponent(BotaoAcessarGeranciaFuncinario)))
					.addContainerGap(24, Short.MAX_VALUE))
		);
		jPanel2.setLayout(jPanel2Layout);

		jPanel3.setBackground(new Color(255, 255, 255));

		jLabel5.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(0, 0, 0));
		jLabel5.setText("Consultar relatório de vendas:");

		jLabel6.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		jLabel6.setForeground(new java.awt.Color(0, 0, 0));
		jLabel6.setText("Inicio da Operações do dia:");

		jLabel8.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		jLabel8.setForeground(new java.awt.Color(0, 0, 0));
		jLabel8.setText("Término das Operações do dia:");

		botaoIniciarDia.setText("Iniciar");

		botaoTerminoDia.setText("Termino");
		if (!app.getBackend().diaEstaAberto())
			botaoTerminoDia.setEnabled(false);
		else
			botaoTerminoDia.setEnabled(true);

		botaoConsultarRelatorio.setText("Consultar relatório");
		//botaoConsultarRelatorio.setEnabled(false);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING).addGroup(jPanel3Layout
				.createSequentialGroup().addGap(185)
				.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel3Layout.createSequentialGroup().addComponent(botaoIniciarDia).addGap(45))
						.addComponent(jLabel6))
				.addPreferredGap(ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
				.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(Alignment.TRAILING,
								jPanel3Layout.createSequentialGroup().addComponent(jLabel8).addGap(156))
						.addGroup(Alignment.TRAILING,
								jPanel3Layout.createSequentialGroup().addComponent(botaoTerminoDia).addGap(207)))
				.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel5).addGroup(
						jPanel3Layout.createSequentialGroup().addGap(24).addComponent(botaoConsultarRelatorio)))
				.addGap(179)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
						.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel3Layout.createSequentialGroup().addGap(19)
										.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
												.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel5)
														.addGap(18).addComponent(botaoConsultarRelatorio))
												.addGroup(jPanel3Layout.createSequentialGroup().addComponent(jLabel6)
														.addGap(18).addComponent(botaoIniciarDia))))
								.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap().addComponent(jLabel8)
										.addGap(18).addComponent(botaoTerminoDia)))
						.addContainerGap(108, Short.MAX_VALUE)));
		jPanel3.setLayout(jPanel3Layout);

		jPanel5.setBackground(new Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("Bem-Vindo a Área do Gerente");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
						.addContainerGap(478, Short.MAX_VALUE).addComponent(jLabel1).addGap(473)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING).addGroup(Alignment.TRAILING,
				jPanel5Layout.createSequentialGroup().addContainerGap(18, Short.MAX_VALUE).addComponent(jLabel1)
						.addContainerGap()));
		jPanel5.setLayout(jPanel5Layout);

		jPanel8.setBackground(new Color(255, 255, 255));

		TXTVendaDeAlimentos.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		TXTVendaDeAlimentos.setForeground(new java.awt.Color(0, 0, 0));
		TXTVendaDeAlimentos.setText("Venda de Alimentos");

		BotaoAcessarVendaDeAlimentos.setText("Acessar");
		if (!app.getBackend().diaEstaAberto())
			BotaoAcessarVendaDeAlimentos.setEnabled(false);
		else
			BotaoAcessarVendaDeAlimentos.setEnabled(true);
		BotaoAcessarVendaDeAlimentos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				BotaoVendaDealimentosActionPerformed(evt);
			}
		});
		
		ImageIcon iconeVendaDeAlimentoParcial = new ImageIcon(getClass().getResource("/img/VendaDeAlimento.png"));
    	Image imgIconeVendaDeAlimentoParcial = iconeVendaDeAlimentoParcial.getImage().getScaledInstance(100, 60, Image.SCALE_SMOOTH);
    	ImageIcon iconeVendaDeAlimento = new ImageIcon(imgIconeVendaDeAlimentoParcial);
		
		lblVendaDeAlimento = new JLabel(iconeVendaDeAlimento);

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8Layout.setHorizontalGroup(
			jPanel8Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblVendaDeAlimento, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
					.addGap(25)
					.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
							.addGap(24)
							.addComponent(BotaoAcessarVendaDeAlimentos))
						.addComponent(TXTVendaDeAlimentos))
					.addContainerGap(169, Short.MAX_VALUE))
		);
		jPanel8Layout.setVerticalGroup(
			jPanel8Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup()
					.addGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel8Layout.createSequentialGroup()
							.addGap(35)
							.addComponent(TXTVendaDeAlimentos)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(BotaoAcessarVendaDeAlimentos))
						.addGroup(jPanel8Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(lblVendaDeAlimento, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(17, Short.MAX_VALUE))
		);
		jPanel8.setLayout(jPanel8Layout);

		jPanel10.setBackground(new Color(255, 255, 255));

		jLabel3.setFont(new Font("Segoe UI", Font.BOLD, 13)); // NOI18N
		jLabel3.setForeground(new java.awt.Color(0, 0, 0));
		jLabel3.setText("Venda de ingressos");

		botaoAcessoCompraDeIngresos.setText("Acessar");
		if (!app.getBackend().diaEstaAberto())
			botaoAcessoCompraDeIngresos.setEnabled(false);
		else
			botaoAcessoCompraDeIngresos.setEnabled(true);
		
		ImageIcon iconeVendaDeIngressoParcial = new ImageIcon(getClass().getResource("/img/VendaDeIngresso.png"));
    	Image imgIconeVendaDeIngressoParcial = iconeVendaDeIngressoParcial.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
    	ImageIcon iconeVendaDeIngresso = new ImageIcon(imgIconeVendaDeIngressoParcial);
		
		lblVendaDeIngresso = new JLabel(iconeVendaDeIngresso);

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
		jPanel10Layout.setHorizontalGroup(
			jPanel10Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel10Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblVendaDeIngresso, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
					.addGap(36)
					.addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jLabel3)
						.addGroup(jPanel10Layout.createSequentialGroup()
							.addGap(15)
							.addComponent(botaoAcessoCompraDeIngresos)))
					.addContainerGap(89, Short.MAX_VALUE))
		);
		jPanel10Layout.setVerticalGroup(
			jPanel10Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel10Layout.createSequentialGroup()
					.addGroup(jPanel10Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel10Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(lblVendaDeIngresso, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel10Layout.createSequentialGroup()
							.addGap(30)
							.addComponent(jLabel3)
							.addGap(18)
							.addComponent(botaoAcessoCompraDeIngresos)))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel10.setLayout(jPanel10Layout);

		JPanel jPanel2_1 = new JPanel();
		jPanel2_1.setBackground(new Color(255, 255, 255));

		BotaoAcessarGeranciaDeFilmes.setText("Acessar");
		if (!app.getBackend().diaEstaAberto())
			BotaoAcessarGeranciaDeFilmes.setEnabled(true);
		else
			BotaoAcessarGeranciaDeFilmes.setEnabled(false);

		JLabel jLabel2_1 = new JLabel();
		jLabel2_1.setBackground(new Color(0, 0, 0));
		jLabel2_1.setText("Seção de Gerenciamento de Filmes");
		jLabel2_1.setForeground(Color.BLACK);
		jLabel2_1.setFont(new Font("Segoe UI", Font.BOLD, 13));
		
		ImageIcon iconeGerenciamentoDeFilmeParcial = new ImageIcon(getClass().getResource("/img/GerenciamentoDeFilme.png"));
    	Image imgIconeGerenciamentoDeFilmeParcial = iconeGerenciamentoDeFilmeParcial.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
    	ImageIcon iconeGerenciamentoDeFilme = new ImageIcon(imgIconeGerenciamentoDeFilmeParcial);
    	
		lblGerenciamentoDeFilme = new JLabel(iconeGerenciamentoDeFilme);
		GroupLayout gl_jPanel2_1 = new GroupLayout(jPanel2_1);
		gl_jPanel2_1.setHorizontalGroup(
			gl_jPanel2_1.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanel2_1.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_jPanel2_1.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_jPanel2_1.createSequentialGroup()
							.addComponent(lblGerenciamentoDeFilme, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(BotaoAcessarGeranciaDeFilmes))
						.addComponent(jLabel2_1))
					.addContainerGap(12, Short.MAX_VALUE))
		);
		gl_jPanel2_1.setVerticalGroup(
			gl_jPanel2_1.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanel2_1.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel2_1)
					.addGroup(gl_jPanel2_1.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_jPanel2_1.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(lblGerenciamentoDeFilme, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE))
						.addGroup(gl_jPanel2_1.createSequentialGroup()
							.addGap(52)
							.addComponent(BotaoAcessarGeranciaDeFilmes)))
					.addContainerGap(41, Short.MAX_VALUE))
		);
		jPanel2_1.setLayout(gl_jPanel2_1);

		jPanel2_2 = new JPanel();
		jPanel2_2.setBackground(new Color(255, 255, 255));
		BotaoAcessarGeranciaDeAlimentos = new javax.swing.JButton();
		Estilizador.aplicarEstiloBotao(BotaoAcessarGeranciaDeAlimentos, EstiloBotao.PADRAO_ESCURECIDO);
		BotaoAcessarGeranciaDeAlimentos.setFont(new Font("Tahoma", Font.BOLD, 12));

		BotaoAcessarGeranciaDeAlimentos.setText("Acessar");
		if (!app.getBackend().diaEstaAberto())
			BotaoAcessarGeranciaDeAlimentos.setEnabled(true);
		else
			BotaoAcessarGeranciaDeAlimentos.setEnabled(false);
		BotaoAcessarGeranciaDeAlimentos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButaoAcessarGeranciaDeAlimentosActionPerformed(evt);
			}
		});

		jLabel4 = new JLabel();
		jLabel4.setText("Seção Gerenciamento de Alimentos");
		jLabel4.setForeground(Color.BLACK);
		jLabel4.setFont(new Font("Segoe UI", Font.BOLD, 13));
		
		ImageIcon iconeGerenciamentoDeAlimentoParcial = new ImageIcon(getClass().getResource("/img/GerenciamentoDeAlimento.png"));
    	Image imgIconeGerenciamentoDeAlimentoParcial = iconeGerenciamentoDeAlimentoParcial.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
    	ImageIcon iconeGerenciamentoDeAlimento = new ImageIcon(imgIconeGerenciamentoDeAlimentoParcial);
		
		lblGerenciamentoDeAlimento = new JLabel(iconeGerenciamentoDeAlimento);
		
		GroupLayout gl_jPanel2_2 = new GroupLayout(jPanel2_2);
		gl_jPanel2_2.setHorizontalGroup(
			gl_jPanel2_2.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanel2_2.createSequentialGroup()
					.addContainerGap()
					.addGroup(gl_jPanel2_2.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_jPanel2_2.createSequentialGroup()
							.addComponent(lblGerenciamentoDeAlimento, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(BotaoAcessarGeranciaDeAlimentos))
						.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 221, GroupLayout.PREFERRED_SIZE))
					.addContainerGap(11, Short.MAX_VALUE))
		);
		gl_jPanel2_2.setVerticalGroup(
			gl_jPanel2_2.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanel2_2.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
					.addGroup(gl_jPanel2_2.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_jPanel2_2.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(lblGerenciamentoDeAlimento, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))
						.addGroup(gl_jPanel2_2.createSequentialGroup()
							.addGap(53)
							.addComponent(BotaoAcessarGeranciaDeAlimentos)))
					.addContainerGap(21, Short.MAX_VALUE))
		);
		jPanel2_2.setLayout(gl_jPanel2_2);
		
		btnVoltar = new JButton("Voltar");
		Estilizador.aplicarEstiloBotao(btnVoltar, EstiloBotao.CLARO_UNIFICADO);
		btnVoltar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				
				TelaLogin loginDeAcesso = new TelaLogin();
				loginDeAcesso.setVisible(true);
				loginDeAcesso.setLocationRelativeTo(null);
				
				dispose();
				
			}
		});
		btnVoltar.setFont(new Font("Tahoma", Font.BOLD, 13));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(36)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(98)
							.addComponent(jPanel2_1, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(49)
							.addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, 365, GroupLayout.PREFERRED_SIZE)))
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, 393, GroupLayout.PREFERRED_SIZE)
							.addGap(92))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(20)
							.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
							.addComponent(jPanel2_2, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
							.addGap(124))))
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(10)
							.addComponent(btnVoltar, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))
						.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE))
					.addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2_1, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE)
						.addComponent(jPanel2_2, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
					.addGap(26)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jPanel8, GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
						.addComponent(jPanel10, GroupLayout.PREFERRED_SIZE, 136, Short.MAX_VALUE))
					.addGap(18)
					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addComponent(btnVoltar)
					.addGap(25))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void ButaoAcessarGeranciaDeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButaoAcessarGeranciaDeFuncionarioActionPerformed
		IBancoDeDadosFuncionario banco = ControladorDeApp.getInstancia()
										.getBackend().getBancoFuncionarios();
		
		TelaCrudFuncionario telaCrudFuncionario = new TelaCrudFuncionario(banco);
		telaCrudFuncionario.setLocationRelativeTo(null);
		telaCrudFuncionario.setVisible(true);
		this.dispose(); // Fecha a tela atual se quiser
	}// GEN-LAST:event_ButaoAcessarGeranciaDeFuncionarioActionPerformed

	private void ButaoAcessarGeranciaDeAlimentosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButaoAcessarGeranciaDeAlimentosActionPerformed
		TelaCrudAlimento gerenciamento = new TelaCrudAlimento();
		gerenciamento.setLocationRelativeTo(null);
		gerenciamento.setVisible(true); // Torna a janela Vendas visível
		this.dispose(); // Fecha a janela atual
	}// GEN-LAST:event_ButaoAcessarGeranciaDeAlimentosActionPerformed

	private void BotaoVendaDealimentosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotaoVendaDealimentosActionPerformed
		TelaVendaDeAlimento vendas = new TelaVendaDeAlimento();
		vendas.setLocationRelativeTo(null);
		vendas.setVisible(true); // Torna a janela Vendas visível
		this.dispose(); // Fecha a janela atual
	}// GEN-LAST:event_BotaoVendaDealimentosActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		throw new UnsupportedOperationException("Não pode iniciar nessa tela!");
		
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		/*try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Gerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} 
		// </editor-fold>

		/* Create and display the form */
		/*java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Gerente telaGerente = new Gerente();
				telaGerente.setVisible(true);
				telaGerente.setLocationRelativeTo(null);
			}
		});*/
	}

	// Variables declaration - do not modify
	private javax.swing.JButton BotaoAcessarVendaDeAlimentos;
	private javax.swing.JButton BotaoAcessarGeranciaDeAlimentos;
	private javax.swing.JButton BotaoAcessarGeranciaFuncinario;
	private javax.swing.JLabel TXTVendaDeAlimentos;
	private javax.swing.JButton botaoAcessoCompraDeIngresos;
	private javax.swing.JButton botaoConsultarRelatorio;
	private javax.swing.JButton botaoIniciarDia;
	private javax.swing.JButton botaoTerminoDia;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel8;
	private JPanel jPanel2_2;
	private JLabel jLabel4;
	private JButton btnVoltar;
	private JLabel lblVendaDeIngresso;
	private JLabel lblGerenciamentoDeFilme;
	private JLabel lblGerenciamentoDeFuncionario;
	private JLabel lblGerenciamentoDeAlimento;
	private JLabel lblVendaDeAlimento;
}
